ribbon:
  eureka:
    enabled: false

eureka:
  client:
    registerWithEureka: false

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    bar:
      url: http://localhost:8081
    foo:
      url: http:/localhost:8082

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false