apiVersion: v1
kind: Service
metadata:
  labels:
    run: foo
  name: foo
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    run: foo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: foo
  name: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: foo
  template:
    metadata:
      labels:
        run: foo
    spec:
      containers:
      - image: betterdevlabs/foo:v1
        imagePullPolicy: IfNotPresent
        name: foo
